// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/enzora-redesign/DashboardGrid.tsx": () => import("../components/mockups/enzora-redesign/DashboardGrid.tsx"),
  "./components/mockups/enzora-redesign/HeroLed.tsx": () => import("../components/mockups/enzora-redesign/HeroLed.tsx"),
  "./components/mockups/enzora-redesign/SoftMinimal.tsx": () => import("../components/mockups/enzora-redesign/SoftMinimal.tsx")
};
