const enzora = {
  primary: "#6E75BF",
  primaryDark: "#8879B8",
  bg: "#F8F9FF",
  card: "#FFFFFF",
  input: "#F4F4FB",
  textPrimary: "#1B2A6B",
  textSecondary: "#6B7FA3",
  textWhite: "#FFFFFF",
  normal: "#FFB703",
  normalBg: "#FFF3CD",
  warning: "#FF6B6B",
  warningBg: "#FFF0F0",
  alert: "#EF233C",
  alertBg: "#FDEDF0",
  border: "#E2E8F0",
  navActive: "#6E75BF",
  navInactive: "#A0AEC0",
  tabBg: "#EBEBF5",
  shadow: "rgba(110, 117, 191, 0.12)",
};

export const gradient: [string, string] = [enzora.primary, enzora.primaryDark];

const colors = {
  light: {
    text: enzora.textPrimary,
    tint: enzora.primary,
    background: enzora.bg,
    foreground: enzora.textPrimary,
    card: enzora.card,
    cardForeground: enzora.textPrimary,
    primary: enzora.primary,
    primaryForeground: enzora.textWhite,
    secondary: enzora.tabBg,
    secondaryForeground: enzora.textPrimary,
    muted: enzora.input,
    mutedForeground: enzora.textSecondary,
    accent: enzora.tabBg,
    accentForeground: enzora.textPrimary,
    destructive: enzora.alert,
    destructiveForeground: enzora.textWhite,
    border: enzora.border,
    input: enzora.input,
    textPrimary: enzora.textPrimary,
    primaryDark: enzora.primaryDark,
    textSecondary: enzora.textSecondary,
    textWhite: enzora.textWhite,
    normal: enzora.normal,
    normalBg: enzora.normalBg,
    warning: enzora.warning,
    warningBg: enzora.warningBg,
    alert: enzora.alert,
    alertBg: enzora.alertBg,
    navActive: enzora.navActive,
    navInactive: enzora.navInactive,
    tabBg: enzora.tabBg,
    shadow: enzora.shadow,
    bg: enzora.bg,
  },
  radius: 14,
};

export default colors;
